// Some dummy products
export let products = [
  {productId: 1,
    title: 'Phone',
    type: 'string',
    price: 150,
    description: 'It is a phone.',
    location: 'Bern',
    isSelling: true,
    isAvailable: true,
    isDeliverable: true,
  },
  {productId: 2,
    title: 'Tomato',
    type: 'Fruit',
    price: 160,
    description: 'It is a juicy tomato.',
    location: 'Zürich',
    isSelling: true,
    isAvailable: true,
    isDeliverable: true,
  },
  {productId: 5,
    title: 'Rock',
    type: 'Fruit',
    price: 9999,
    description: 'It is a rock.',
    location: 'Zürich',
    isSelling: true,
    isAvailable: true,
    isDeliverable: false,
  },
];

